# Generated by Django 4.2.5 on 2023-09-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_player_delete_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players_photos'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Obrońca'), (2, 'Pomocnik'), (3, 'Napastnik'), (0, 'Bramkarz')], default=0),
        ),
    ]
