# Generated by Django 4.2.5 on 2023-09-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_player_position_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Obrońca'), (2, 'Pomocnik'), (3, 'Napastnik'), (0, 'Bramkarz')], default=0),
        ),
    ]
